import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import PDFDocument from 'pdfkit';
import { getReportRecords } from './db.js';
import { analyseFeedback } from './aiInsights.js';

const LOGO_PATH = path.join(path.dirname(fileURLToPath(import.meta.url)), '../client/public/logo.png');

function escapeHtml(value) {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

export function rowsToWordHtml(rows, title, staff = null) {
  const tableRows = rows
    .filter((row) => row.length)
    .map(
      (row) =>
        `<tr>${row.map((cell) => `<td>${escapeHtml(cell)}</td>`).join('')}</tr>`
    )
    .join('');
  const generatedBy = staff?.name?.trim() || 'Not specified';
  const email = staff?.email?.trim() || 'Not specified';
  const staffId = staff?.staffId || staff?.loginId || 'Not specified';

  return `<!DOCTYPE html>
<html xmlns:o="urn:schemas-microsoft-com:office:office"
      xmlns:w="urn:schemas-microsoft-com:office:word"
      xmlns="http://www.w3.org/TR/REC-html40">
<head>
  <meta charset="utf-8">
  <title>${escapeHtml(title)}</title>
</head>
<body>
  <h1>${escapeHtml(title)}</h1>
  <p>NexGen University — Student Feedback Collection Platform</p>
  <p>Generated by ${escapeHtml(generatedBy)} (${escapeHtml(email)}, ${escapeHtml(staffId)})</p>
  <table border="1" cellpadding="6" cellspacing="0">${tableRows}</table>
</body>
</html>`;
}

export function rowsToPdfBuffer(rows, title) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const chunks = [];

    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    doc.fontSize(18).text(title, { underline: true });
    doc.moveDown();

    rows.forEach((row) => {
      if (!row.length) {
        doc.moveDown(0.4);
        return;
      }

      doc.fontSize(11).text(row.map((cell) => String(cell ?? '')).join('  |  '), {
        lineGap: 4,
      });
    });

    doc.end();
  });
}

function display(value, fallback = 'Not specified') {
  if (value == null) return fallback;
  const text = String(value).trim();
  if (!text || text === 'undefined' || text === 'null') return fallback;
  return text;
}

function cellText(value) {
  if (value == null) return 'Not specified';
  const text = String(value);
  if (text.trim() === 'undefined' || text.trim() === 'null') return 'Not specified';
  return text;
}

function staffDetails(staff) {
  const generated = new Date();
  return {
    name: display(staff?.name),
    email: display(staff?.email),
    staffId: display(staff?.staffId || staff?.loginId),
    date: generated.toLocaleDateString('en-AU', {
      day: 'numeric',
      month: 'long',
      year: 'numeric',
      timeZone: 'UTC',
    }),
    time: `${generated.toLocaleTimeString('en-AU', {
      hour: '2-digit',
      minute: '2-digit',
      hour12: false,
      timeZone: 'UTC',
    })} UTC`,
  };
}

function contentWidth(doc) {
  return doc.page.width - doc.page.margins.left - doc.page.margins.right;
}

function drawRunningHeader(doc) {
  const left = doc.page.margins.left;
  const width = contentWidth(doc);
  if (fs.existsSync(LOGO_PATH)) {
    doc.image(LOGO_PATH, left, 26, { height: 34 });
  }
  doc.fillColor('#0B3A6A').font('Helvetica-Bold').fontSize(12);
  doc.text('NexGen University', left + 44, 28, { width: width - 44, lineBreak: false });
  doc.fillColor('#3d4f66').font('Helvetica').fontSize(9);
  doc.text('Student Feedback Collection Platform', left + 44, 44, { width: width - 44, lineBreak: false });
  doc.moveTo(left, 68).lineTo(left + width, 68).lineWidth(1.2).strokeColor('#0B3A6A').stroke();
  doc.x = left;
  doc.y = doc.page.margins.top;
}

function addFooters(doc, staff) {
  const range = doc.bufferedPageRange();
  for (let index = 0; index < range.count; index += 1) {
    doc.switchToPage(index);
    const left = doc.page.margins.left;
    const width = contentWidth(doc);
    const generated = `Generated by: ${staff.name}    Generated: ${staff.date}, ${staff.time}`;
    doc.page.margins.bottom = 0;
    doc.save();
    doc.font('Helvetica').fontSize(8).fillColor('#3d4f66');
    doc.text('NexGen University', left, doc.page.height - 50, { width, lineBreak: false });
    doc.text('Student Feedback Collection Platform', left, doc.page.height - 39, { width, lineBreak: false });
    doc.text(generated, left, doc.page.height - 28, { width: width - 70, lineBreak: false });
    doc.text(`Page ${index + 1} of ${range.count}`, left, doc.page.height - 28, {
      width,
      align: 'right',
      lineBreak: false,
    });
    doc.restore();
  }
}

function createDocument() {
  const doc = new PDFDocument({
    size: 'A4',
    bufferPages: true,
    autoFirstPage: false,
    margins: { top: 84, bottom: 68, left: 46, right: 46 },
  });
  doc.on('pageAdded', () => drawRunningHeader(doc));
  doc.addPage();
  return doc;
}

function finishDocument(doc, staff) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
    addFooters(doc, staff);
    doc.end();
  });
}

function ensureSpace(doc, height) {
  if (doc.y + height > doc.page.height - doc.page.margins.bottom) doc.addPage();
}

function heading(doc, text) {
  ensureSpace(doc, 40);
  doc.moveDown(0.55);
  doc.fillColor('#0B3A6A').font('Helvetica-Bold').fontSize(13);
  doc.text(text, { width: contentWidth(doc) });
  const y = doc.y + 2;
  doc.moveTo(doc.page.margins.left, y).lineTo(doc.page.margins.left + contentWidth(doc), y)
    .strokeColor('#C4A35A').lineWidth(1).stroke();
  doc.y = y + 8;
  doc.x = doc.page.margins.left;
}

function paragraph(doc, text) {
  doc.fillColor('#1f2933').font('Helvetica').fontSize(10);
  doc.text(display(text), { width: contentWidth(doc), lineGap: 2 });
  doc.moveDown(0.35);
}

function bulletList(doc, items) {
  if (!items.length) {
    paragraph(doc, 'Not enough evidence in the stored responses.');
    return;
  }
  doc.fillColor('#1f2933').font('Helvetica').fontSize(10);
  for (const item of items) {
    ensureSpace(doc, 28);
    doc.text(`•  ${display(item)}`, {
      width: contentWidth(doc),
      indent: 8,
      lineGap: 2,
    });
    doc.moveDown(0.25);
  }
}

function scaledColumns(doc, specs) {
  const width = contentWidth(doc);
  const total = specs.reduce((sum, column) => sum + column.width, 0);
  return specs.map((column) => ({ ...column, width: (column.width / total) * width }));
}

function drawTable(doc, specs, rows) {
  const columns = scaledColumns(doc, specs);
  const tableWidth = columns.reduce((sum, column) => sum + column.width, 0);
  const left = doc.page.margins.left;
  const padX = 4;
  const padY = 3;

  const rowHeight = (cells, header) => {
    doc.font(header ? 'Helvetica-Bold' : 'Helvetica').fontSize(8);
    let height = 0;
    cells.forEach((cell, index) => {
      const text = cellText(cell);
      height = Math.max(height, doc.heightOfString(text || ' ', { width: columns[index].width - padX * 2 }));
    });
    return height + padY * 2;
  };

  const paint = (cells, header, alt) => {
    const height = rowHeight(cells, header);
    const limit = doc.page.height - doc.page.margins.bottom;
    const room = limit - doc.page.margins.top;
    if (doc.y + height > limit && height <= room) {
      doc.addPage();
      if (!header) paint(columns.map((column) => column.header), true, false);
    }
    const y = doc.y;
    if (header) doc.rect(left, y, tableWidth, height).fill('#0B3A6A');
    else if (alt) doc.rect(left, y, tableWidth, height).fill('#f4f7fb');
    doc.font(header ? 'Helvetica-Bold' : 'Helvetica').fontSize(8).fillColor(header ? '#ffffff' : '#1f2933');
    let x = left;
    cells.forEach((cell, index) => {
      doc.text(cellText(cell), x + padX, y + padY, {
        width: columns[index].width - padX * 2,
        height: Math.max(height - padY * 2, 8),
      });
      doc.y = y;
      x += columns[index].width;
    });
    doc.y = y + height;
    doc.moveTo(left, doc.y).lineTo(left + tableWidth, doc.y).strokeColor(header ? '#0B3A6A' : '#d5dce6').lineWidth(0.4).stroke();
    doc.x = left;
  };

  paint(columns.map((column) => column.header), true, false);
  rows.forEach((row, index) => paint(row, false, index % 2 === 1));
  doc.moveDown(0.45);
}

function renderAnalysisPdf(analysis, staffInfo) {
  const doc = createDocument();
  doc.fillColor('#0B3A6A').font('Helvetica-Bold').fontSize(18);
  doc.text('Student Feedback Analysis Report', { width: contentWidth(doc) });
  doc.moveDown(0.2);
  doc.fillColor('#3d4f66').font('Helvetica').fontSize(10);
  doc.text(display(analysis.reportName), { width: contentWidth(doc) });
  doc.moveDown(0.4);

  heading(doc, 'Report information');
  const infoRows = [
    ['Report / survey name', analysis.reportName],
    ['Generated date', staffInfo.date],
    ['Generated time', staffInfo.time],
    ['Generated by', staffInfo.name],
    ['Staff email', staffInfo.email],
    ['Staff ID', staffInfo.staffId],
    ['Reporting period', analysis.reportingPeriod],
  ];
  if (analysis.surveyClosing) infoRows.push(['Survey closing date', analysis.surveyClosing]);
  drawTable(doc, [
    { header: 'Field', width: 34 },
    { header: 'Value', width: 66 },
  ], infoRows);

  heading(doc, 'Overall summary');
  drawTable(doc, [
    { header: 'Measure', width: 60 },
    { header: 'Value', width: 40 },
  ], [
    ['Total responses', analysis.totals.totalResponses],
    ['Overall average rating', analysis.totals.averageRating == null ? 'Not specified' : analysis.totals.averageRating],
  ]);

  heading(doc, 'Overall results');
  drawTable(doc, [
    { header: 'Statistic', width: 60 },
    { header: 'Value', width: 40 },
  ], [
    ['Total responses', analysis.totals.totalResponses],
    ['Unique students', analysis.totals.uniqueStudents],
    ['Overall average rating', analysis.totals.averageRating == null ? 'Not specified' : `${analysis.totals.averageRating} / 5`],
    ['Rating answers', analysis.totals.ratingAnswerCount],
    ['Written responses', analysis.totals.writtenCount],
    ['Departments represented', analysis.totals.departmentCount],
    ['Programs represented', analysis.totals.programCount],
  ]);

  heading(doc, 'Question-level results');
  const questionsBySurvey = new Map();
  for (const question of analysis.questions) {
    const list = questionsBySurvey.get(question.surveyTitle) || [];
    list.push(question);
    questionsBySurvey.set(question.surveyTitle, list);
  }
  if (!questionsBySurvey.size) {
    paragraph(doc, 'No question results are available.');
  }
  for (const [surveyTitle, questions] of questionsBySurvey) {
    ensureSpace(doc, 72);
    doc.fillColor('#0B3A6A').font('Helvetica-Bold').fontSize(11);
    doc.text(display(surveyTitle), { width: contentWidth(doc) });
    doc.moveDown(0.25);
    drawTable(doc, [
      { header: 'Question', width: 30 },
      { header: 'Type', width: 12 },
      { header: 'Responses', width: 12 },
      { header: 'Average', width: 12 },
      { header: 'Result / summary', width: 34 },
    ], questions.map((question) => [
      question.questionText,
      question.questionType,
      question.responseCount,
      question.questionType === 'Rating' ? (question.averageRating == null ? 'Not specified' : String(question.averageRating)) : 'Not applicable',
      question.summary,
    ]));
  }

  heading(doc, 'Rating analysis');
  paragraph(
    doc,
    analysis.ratingAnalysis.averageRating == null
      ? 'No rating answers are stored for this report.'
      : `Average rating ${analysis.ratingAnalysis.averageRating} out of 5 from ${analysis.ratingAnalysis.responseCount} rating answers.`
  );
  drawTable(doc, [
    { header: 'Rating', width: 30 },
    { header: 'Number of responses', width: 40 },
    { header: 'Percentage', width: 30 },
  ], analysis.ratingAnalysis.distribution.map((row) => [
    row.label,
    row.count,
    `${row.percentage}%`,
  ]));

  heading(doc, 'Written feedback analysis');
  paragraph(doc, `Total written responses: ${analysis.writtenFeedbackAnalysis.totalWritten}.`);
  drawTable(doc, [
    { header: 'Theme', width: 34 },
    { header: 'Responses', width: 16 },
    { header: 'What students wrote', width: 50 },
  ], analysis.themes.length
    ? analysis.themes.map((theme) => [theme.name, theme.count, theme.explanation])
    : [['Not specified', '0', 'Not enough written feedback to identify a theme.']]);
  heading(doc, 'Positive themes');
  bulletList(doc, analysis.positiveFeedback.map((theme) => `${theme.name} (${theme.count}). ${theme.explanation}`));
  heading(doc, 'Areas for improvement');
  bulletList(doc, analysis.areasForImprovement.map((theme) => `${theme.name} (${theme.count}). ${theme.explanation}`));

  heading(doc, 'AI insights');
  doc.fillColor('#0B3A6A').font('Helvetica-Bold').fontSize(11);
  ensureSpace(doc, 36);
  doc.text('Overall AI summary', { width: contentWidth(doc) });
  doc.moveDown(0.2);
  paragraph(doc, analysis.summary);

  doc.fillColor('#0B3A6A').font('Helvetica-Bold').fontSize(11);
  ensureSpace(doc, 36);
  doc.text('Key themes', { width: contentWidth(doc) });
  doc.moveDown(0.2);
  bulletList(doc, analysis.themes.map((theme) => `${theme.name} — ${theme.count} responses. ${theme.explanation}`));

  doc.fillColor('#0B3A6A').font('Helvetica-Bold').fontSize(11);
  ensureSpace(doc, 36);
  doc.text('Positive feedback', { width: contentWidth(doc) });
  doc.moveDown(0.2);
  bulletList(doc, analysis.positiveFeedback.map((theme) => `${theme.name} — ${theme.count} responses. ${theme.explanation}`));

  doc.fillColor('#0B3A6A').font('Helvetica-Bold').fontSize(11);
  ensureSpace(doc, 36);
  doc.text('Areas for improvement', { width: contentWidth(doc) });
  doc.moveDown(0.2);
  bulletList(doc, analysis.areasForImprovement.map((theme) => `${theme.name} — ${theme.count} responses. ${theme.explanation}`));

  doc.fillColor('#0B3A6A').font('Helvetica-Bold').fontSize(11);
  ensureSpace(doc, 36);
  doc.text('Recommended actions', { width: contentWidth(doc) });
  doc.moveDown(0.2);
  bulletList(doc, analysis.recommendations);

  doc.fillColor('#0B3A6A').font('Helvetica-Bold').fontSize(11);
  ensureSpace(doc, 36);
  doc.text('Department / program insights', { width: contentWidth(doc) });
  doc.moveDown(0.2);
  bulletList(doc, analysis.departmentInsights.map((program) => (
    `${program.name}: ${program.responseCount} responses, average rating ${program.averageRating == null ? 'Not specified' : program.averageRating}. ${program.insight}`
  )));

  heading(doc, 'Department / program table');
  drawTable(doc, [
    { header: 'Department / program', width: 34 },
    { header: 'Responses', width: 14 },
    { header: 'Average rating', width: 16 },
    { header: 'Key insight', width: 36 },
  ], analysis.departmentInsights.length
    ? analysis.departmentInsights.map((program) => [
      program.name,
      program.responseCount,
      program.averageRating == null ? 'Not specified' : program.averageRating,
      program.insight,
    ])
    : [['Not specified', '0', 'Not specified', 'No responses are available.']]);

  return finishDocument(doc, staffInfo);
}

function renderRosterPdf(staffInfo) {
  const records = getReportRecords();
  const doc = createDocument();
  doc.fillColor('#0B3A6A').font('Helvetica-Bold').fontSize(18);
  doc.text('Student Feedback Analysis Report', { width: contentWidth(doc) });
  doc.moveDown(0.2);
  doc.fillColor('#3d4f66').font('Helvetica').fontSize(10);
  doc.text('Student response register', { width: contentWidth(doc) });
  heading(doc, 'Report information');
  drawTable(doc, [
    { header: 'Field', width: 34 },
    { header: 'Value', width: 66 },
  ], [
    ['Report / survey name', 'Student response register'],
    ['Generated date', staffInfo.date],
    ['Generated time', staffInfo.time],
    ['Generated by', staffInfo.name],
    ['Staff email', staffInfo.email],
    ['Staff ID', staffInfo.staffId],
    ['Total responses', records.responses.length],
  ]);
  heading(doc, 'Responses');
  drawTable(doc, [
    { header: 'Student', width: 22 },
    { header: 'Survey', width: 28 },
    { header: 'Department / program', width: 30 },
    { header: 'Submitted', width: 20 },
  ], records.responses.map((response) => {
    const department = response.department_name || 'Not specified';
    const program = response.course_code && response.course_name
      ? `${response.course_code} ${response.course_name}`
      : response.course_name || response.course_code || 'Not specified';
    const programLabel = department === 'Not specified' && program === 'Not specified'
      ? 'Not specified'
      : `${department} — ${program}`;
    return [
      response.is_anonymous ? 'Anonymous student' : (response.student_name || 'Not specified'),
      response.survey_title,
      programLabel,
      response.submitted_at || 'Not specified',
    ];
  }));
  return finishDocument(doc, staffInfo);
}

export function renderStaffPdf({ type, id = null, staff }) {
  const staffInfo = staffDetails(staff);
  if (type === 'responses') return renderRosterPdf(staffInfo);

  const scope = {};
  if (type === 'survey') scope.surveyId = id;
  if (type === 'department') scope.departmentId = id;
  if (type === 'course') scope.courseId = id;
  if (!['university', 'survey', 'department', 'course'].includes(type)) return null;

  const records = getReportRecords(scope);
  return renderAnalysisPdf(analyseFeedback(records), staffInfo);
}
